package com.openclassrooms.mddapi.models;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.ToString;
import lombok.experimental.Accessors;

import javax.persistence.*;
import java.time.LocalDateTime;

/**
 * Entity representing a comment in the MDD application, created by a user and
 * related to a post
 */
@Entity
@Table(name = "COMMENTS")
@Data
@Accessors(chain = true)
@EntityListeners(AuditingEntityListener.class)
@EqualsAndHashCode(of = { "id" })
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Comment {

    /** Primary key, autogenerated */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** User who created the comment */
    @NonNull
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /** Post the comment is related to */
    @NonNull
    @ManyToOne
    @JoinColumn(name = "post_id")
    private Post post;

    /** Comment content */
    @NonNull
    @Lob
    private String content;

    /** Timestamp of creation */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

}
