package com.openclassrooms.mddapi.models;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.ToString;
import lombok.experimental.Accessors;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;

/**
 * Entity representing a post in the MDD application, created by a user and
 * related to a topic
 */
@Entity
@Table(name = "POSTS")
@Data
@Accessors(chain = true)
@EntityListeners(AuditingEntityListener.class)
@EqualsAndHashCode(of = { "id" })
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Post {

    /** Primary key, autogenerated */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Post title */
    @NonNull
    @Size(max = 100)
    private String title;

    /** Post content */
    @NonNull
    @Lob
    private String content;

    /** User who created the post */
    @NonNull
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /** Topic the post is related to */
    @NonNull
    @ManyToOne
    @JoinColumn(name = "topic_id")
    private Topic topic;

    /** Timestamp of creation */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of last update */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Initializes `createdAt` and `updatedAt` before persisting */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    /** Updates `updatedAt` before updating */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

}
