package com.openclassrooms.mddapi.models;

import lombok.*;
import lombok.experimental.Accessors;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import javax.validation.constraints.Email;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity representing a user of the MDD application, who create posts and
 * comments
 */
@Entity
@Table(name = "USERS", uniqueConstraints = {
        @UniqueConstraint(columnNames = { "email", "user_name" })
})
@Data
@Accessors(chain = true)
@EntityListeners(AuditingEntityListener.class)
@EqualsAndHashCode(of = { "id" })
@Builder
@NoArgsConstructor
@RequiredArgsConstructor
@AllArgsConstructor
@ToString
public class User {

    /** Primary key, autogenerated */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** User email, can be used as login for authentication */
    @NonNull
    @Size(max = 50)
    @Email
    private String email;

    /** User name, can be used as login for authentication */
    @NonNull
    @Size(max = 20)
    @Column(name = "user_name")
    private String userName;

    /** Encrypted password */
    @NonNull
    @Size(max = 120)
    private String password;

    /** List of topics the user is subscribed to */
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "SUBSCRIPTIONS", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "topic_id"))
    @Builder.Default
    private List<Topic> subscriptions = new ArrayList<>();

    /** List of post for user feed */
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "FEEDS", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "post_id"))
    @OrderBy("createdAt DESC")
    @Builder.Default
    private List<Post> feed = new ArrayList<>();

    /** Timestamp of creation, set once and not updatable. */
    @CreatedDate
    @Column(name = "created_at", updatable = false, nullable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last update. */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /** Initializes `createdAt` and `updatedAt` before persisting */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

}
