spring.application.name=mddapi

#Mysql Database conf
spring.datasource.url=${MYSQL_DATABASE_URL_MDDAPP}
spring.datasource.username=${MYSQL_DATABASE_USERNAME}
spring.datasource.password=${MYSQL_DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true