package com.openclassrooms.mddapi.payload.response;

import lombok.Data;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;

/**
 * DTO with the token for authentificated user
 */
@Data
@RequiredArgsConstructor
public class TokenResponse {

    /**
     * The token generated by JWTService
     */
    @NonNull
    private String token;
}
